import localFont from "next/font/local";
import "./globals.css";
import '@fortawesome/fontawesome-free/css/all.min.css';
import "primereact/resources/themes/lara-light-cyan/theme.css";
import Tailwind from 'primereact/passthrough/tailwind';
import {
    Roboto
} from "next/font/google";
import {PrimeReactProvider} from "primereact/api";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});
const roboto = Roboto({
    weight: '400',
    subsets: ['latin'],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en" className={roboto.className}>
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <PrimeReactProvider value={{pt: Tailwind}}>
            {children}
        </PrimeReactProvider>
        </body>
        </html>
    );
}
