import localFont from "next/font/local";
import "./globals.css";
import '@fortawesome/fontawesome-free/css/all.min.css';
import "primereact/resources/themes/lara-light-cyan/theme.css";
import Tailwind from 'primereact/passthrough/tailwind';

import {
    Roboto
} from "next/font/google";
import {PrimeReactProvider} from "primereact/api";
import Head from "next/head";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});
const roboto = Roboto({
    weight: '400',
    subsets: ['latin'],
});

export const metadata = {
    title: "Əhli sünnə mədrəsəsi",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    const domain = process.env.NEXT_PUBLIC_DOMAIN;
    return (
        <html lang="en" className={roboto.className}>
        <head>
            <meta httpEquiv="Content-Security-Policy" content="upgrade-insecure-requests"/>
            <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests"/>
        </head>
        <Head>
            <link rel="canonical" href={domain}/>
            <link rel="preconnect" href="https://fonts.googleapis.com"/>
            <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true"/>
            <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap"/>
            {/*<meta httpEquiv="Content-Security-Policy" content="upgrade-insecure-requests"/>*/}
        </Head>
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <PrimeReactProvider value={{pt: Tailwind}}>
            {children}
        </PrimeReactProvider>
        </body>
        </html>
    );
}
