import React, { useEffect, useState } from 'react'
import Head from 'next/head'
import { Poppins } from 'next/font/google'
import { trpc } from '@/server/utils/trpc';


const montserrat = Poppins({ weight: ["400", "500", "600", "700"], subsets: ["latin-ext"] })

export default function Home(props: any) {

  const p = trpc.playlist.getAll.useQuery(undefined, { staleTime: 86400000, });
  const v1 = trpc.video.oneByVideoId.useQuery("jj81sPdd8fk");





  return (
    <>
      <Header />
      <main className={montserrat.className} >
        <div className='homePage  ' >
          Əhli Sünnə Mədrəsəsi
        </div>
      </main>

    </>
  )
}

const Header = () => (
  <Head>
    <title>Əhli Sünnə Mədrəsəsi</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
)
